name: teste
services:
  web:
    build: 
      context: ./app
      target: web
    ports:
      - "3000:3000"
    develop:
      watch:
      - path: ./
        action: sync
        target: ./app
      - path: ./package.json
        action: rebuild

  server:
    build: 
      context: ./app
      target: server
    develop:
      watch:
      - path: ./server
        action: sync
        target: ./app
      - path: ./server/package.json
        action: rebuild
    